//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLibraryTest.CrystalServiceLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrystalServiceLocal.ICrystalService")]
    public interface ICrystalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrystalService/CreateDocumentSync", ReplyAction="http://tempuri.org/ICrystalService/CreateDocumentSyncResponse")]
        byte[] CreateDocumentSync(Dcf.Kids.Reporting.ServiceLibrary.DocumentRequest request, Dcf.Kids.Reporting.ServiceLibrary.ReportParameterEntity[] collect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrystalService/CreateDocumentSync", ReplyAction="http://tempuri.org/ICrystalService/CreateDocumentSyncResponse")]
        System.Threading.Tasks.Task<byte[]> CreateDocumentSyncAsync(Dcf.Kids.Reporting.ServiceLibrary.DocumentRequest request, Dcf.Kids.Reporting.ServiceLibrary.ReportParameterEntity[] collect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrystalService/TestConnection", ReplyAction="http://tempuri.org/ICrystalService/TestConnectionResponse")]
        string TestConnection(string testString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrystalService/TestConnection", ReplyAction="http://tempuri.org/ICrystalService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync(string testString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrystalServiceChannel : ServiceLibraryTest.CrystalServiceLocal.ICrystalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrystalServiceClient : System.ServiceModel.ClientBase<ServiceLibraryTest.CrystalServiceLocal.ICrystalService>, ServiceLibraryTest.CrystalServiceLocal.ICrystalService {
        
        public CrystalServiceClient() {
        }
        
        public CrystalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrystalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrystalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrystalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] CreateDocumentSync(Dcf.Kids.Reporting.ServiceLibrary.DocumentRequest request, Dcf.Kids.Reporting.ServiceLibrary.ReportParameterEntity[] collect) {
            return base.Channel.CreateDocumentSync(request, collect);
        }
        
        public System.Threading.Tasks.Task<byte[]> CreateDocumentSyncAsync(Dcf.Kids.Reporting.ServiceLibrary.DocumentRequest request, Dcf.Kids.Reporting.ServiceLibrary.ReportParameterEntity[] collect) {
            return base.Channel.CreateDocumentSyncAsync(request, collect);
        }
        
        public string TestConnection(string testString) {
            return base.Channel.TestConnection(testString);
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync(string testString) {
            return base.Channel.TestConnectionAsync(testString);
        }
    }
}
